version: "3.8"

services:
   api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      command: python3 manage.py runserver 0.0.0.0:8000
      volumes:
         - .:/app
      # ports:
      #    - 8000:8000
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - spatial_analysis_api

   postgres-db:
      image: kartoza/postgis:12.0
      ports:
         - 5432:5432
      volumes:
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      restart: "on-failure"
      networks:
         - spatial_analysis_api

   nginx:
      restart: always
      depends_on:
         - api
      build:
         context: ./nginx
         dockerfile: Dockerfile.dev
      ports:
         - 8080:80
      networks:
         - spatial_analysis_api

networks:
   spatial_analysis_api:
      driver: bridge

volumes:
   postgres_data:
